from aiogram import Router, types
from aiogram import F 
from aiogram.filters import MagicData

from bot_instance import GuestStates, LoggedInStates
from handlers.messages.msg_login import msg_login_1_ask_credentials
from handlers.messages.msg_contact import msg_contact
from handlers.middlewares.authenticated_session import AuthenticatedSessionMiddleware
from handlers.middlewares.verify_contact import VerifyContactMiddleware
from handlers.middlewares.register_middleware import RegisterSessionMiddleware
from handlers.messages.msg_register import msg_register_1_username, msg_register_2_password, msg_register_3_bank_name, msg_register_4_bank_account_name, msg_register_5_bank_account_number
from handlers.messages.msg_deposit import msg_deposit_ask_amount


message_router = Router()

# Add contact verification middleware to all message handlers
message_router.message.middleware(VerifyContactMiddleware())

# Contact message handler
register_router = Router()
register_router.message.middleware(RegisterSessionMiddleware())
register_router.message.register(msg_contact, F.contact)
register_router.message.register(msg_register_1_username, GuestStates.register_1_ask_username)
register_router.message.register(msg_register_1_username, GuestStates.register_1_edit_username)
register_router.message.register(msg_register_2_password, GuestStates.register_2_ask_password)
register_router.message.register(msg_register_2_password, GuestStates.register_2_edit_password)
register_router.message.register(msg_register_3_bank_name, GuestStates.register_3_ask_bank_name)
register_router.message.register(msg_register_3_bank_name, GuestStates.register_3_edit_bank_name)
register_router.message.register(msg_register_4_bank_account_name, GuestStates.register_4_ask_bank_account_name)
register_router.message.register(msg_register_4_bank_account_name, GuestStates.register_4_edit_bank_account_name)
register_router.message.register(msg_register_5_bank_account_number, GuestStates.register_5_ask_bank_account_number)
register_router.message.register(msg_register_5_bank_account_number, GuestStates.register_5_edit_bank_account_number)
message_router.include_router(register_router)

login_router = Router()
login_router.message.register(msg_login_1_ask_credentials, GuestStates.login_1_ask_credentials)
message_router.include_router(login_router)
# message_router.message.register(msg_register_6_confirm_register, GuestStates.register_6_ask_confirm_register)

authenticated_only_router = Router()
authenticated_only_router.message.middleware(AuthenticatedSessionMiddleware())
message_router.include_router(authenticated_only_router)
authenticated_only_router.message.register(msg_deposit_ask_amount, LoggedInStates.deposit_ask_amount)